PUT http://localhost:8080/api/user/update_user
Authorization: {{token}}
Refresh-Token: {{refresh-token}}
Content-Type: application/json

{
    "email" : "naufalulwan63@gmail.com",
    "phone" : "082124293938",
    "address" : "Jl. Puskesmas No.170 RT.04/RW.10, Kranji, Bekasi Barat, Bekasi, Jawat Barat 17135",
    "position": "Manajer/Lead Tech"
}
