version: "3"

services:
  barcation:
    image: barcation
    container_name: app_barcation
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 8080:8080
    depends_on:
      - postgres
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - .:/go/src/barcation
    networks:
      - network

  postgres:
    image: postgres
    container_name: db_barcation
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always
    ports:
      - 5432:5432
    volumes:
      - pgdb:/var/lib/postgresql/data
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  pgdb:
