POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "Admin123*",
  "device_id": "Android AP31312Z",
  "is_save_info": true
}

> {%
  const responseBody = response.body;

  if (responseBody.authorization != null) {
    client.global.set("token", `Bearer ${responseBody.authorization.token}`);
    client.global.set("refresh-token", `Bearer ${responseBody.authorization.refresh_token}`);
  }
%}

